from __future__ import annotations
import os
import plistlib
import subprocess
import sys
from pathlib import Path
from typing import Optional

PLIST_LABEL = "local.new-ebooks.check"
PLIST_PATH = Path.home() / "Library" / "LaunchAgents" / f"{PLIST_LABEL}.plist"
_CONFIG_DIR = Path.home() / ".config" / "new_ebooks"
LAUNCHER_PATH = _CONFIG_DIR / "launcher.py"
PKG_CACHE_DIR = _CONFIG_DIR / "pkg"

WEEKDAY_NAMES = ["Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"]


def _cache_package() -> None:
    """Copy the new_ebooks source to ~/.config/new_ebooks/pkg/.

    launchd agents lack the entitlement to access iCloud Drive paths
    (PermissionError even on locally-downloaded files). Copying the package
    at schedule-time — when the interactive process has iCloud Drive access —
    puts the source in a regular directory that launchd can always read.
    """
    import new_ebooks as _pkg
    import shutil

    src_dir = Path(_pkg.__path__[0])
    dst_dir = PKG_CACHE_DIR / "new_ebooks"
    if dst_dir.exists():
        shutil.rmtree(dst_dir)
    shutil.copytree(src_dir, dst_dir)


def write_launcher() -> None:
    _cache_package()

    site_pkgs = [p for p in sys.path if "site-packages" in p and p and Path(p).exists()]
    # PKG_CACHE_DIR first so the local copy is found before the editable-install
    # stub in site-packages (which would redirect back to the iCloud path).
    extra_paths = [str(PKG_CACHE_DIR)] + site_pkgs
    paths_repr = repr(extra_paths)

    # Diagnostic block: on ImportError, log Python version, sys.path, and
    # where new_ebooks resolves to, so the root cause can be determined.
    diag = (
        "except Exception as _e:\n"
        "    import importlib.util as _ilu, os as _os\n"
        "    print(f'[new-ebooks] ImportError: {_e}', file=_sys.stderr)\n"
        "    print(f'[new-ebooks] Python: {_sys.version}', file=_sys.stderr)\n"
        "    print(f'[new-ebooks] executable: {_sys.executable}', file=_sys.stderr)\n"
        "    print(f'[new-ebooks] sys.path: {_sys.path}', file=_sys.stderr)\n"
        "    _spec = _ilu.find_spec('new_ebooks')\n"
        "    if _spec:\n"
        "        print(f'[new-ebooks] new_ebooks origin: {_spec.origin}', file=_sys.stderr)\n"
        "        print(f'[new-ebooks] new_ebooks __path__: {list(_spec.submodule_search_locations or [])}', file=_sys.stderr)\n"
        "        _pd = (list(_spec.submodule_search_locations) or [''])[0]\n"
        "        if _pd:\n"
        "            print(f'[new-ebooks] package dir: {sorted(_os.listdir(_pd))}', file=_sys.stderr)\n"
        "    else:\n"
        "        print('[new-ebooks] new_ebooks not found by importlib', file=_sys.stderr)\n"
        "    _sys.exit(1)\n"
    )

    launcher = (
        "# Auto-generated by `new-ebooks schedule`. Do not edit.\n"
        "import sys as _sys\n"
        "_sys.stdout.reconfigure(line_buffering=True)\n"
        f"for _p in {paths_repr}:\n"
        "    if _p not in _sys.path:\n"
        "        _sys.path.insert(0, _p)\n"
        "try:\n"
        "    from new_ebooks.cli import main\n"
        + diag +
        "else:\n"
        "    _sys.exit(main())\n"
    )
    LAUNCHER_PATH.parent.mkdir(parents=True, exist_ok=True)
    LAUNCHER_PATH.write_text(launcher)


def write_plist(check_args: list[str], weekday: int, hour: int, minute: int, log_path: Path) -> None:
    PLIST_PATH.parent.mkdir(parents=True, exist_ok=True)
    write_launcher()

    plist = {
        "Label": PLIST_LABEL,
        "ProgramArguments": [sys.executable, str(LAUNCHER_PATH), "check"] + check_args,
        "StartCalendarInterval": {
            "Weekday": weekday,
            "Hour": hour,
            "Minute": minute,
        },
        "StandardOutPath": str(log_path),
        "StandardErrorPath": str(log_path),
    }
    with open(PLIST_PATH, "wb") as f:
        plistlib.dump(plist, f)


def _gui_target() -> str:
    return f"gui/{os.getuid()}"


def load_plist() -> None:
    subprocess.run(
        ["launchctl", "bootstrap", _gui_target(), str(PLIST_PATH)],
        check=True, capture_output=True, text=True,
    )


def unload_plist() -> None:
    subprocess.run(
        ["launchctl", "bootout", _gui_target(), str(PLIST_PATH)],
        capture_output=True, text=True,  # don't raise — may not be loaded
    )


def is_loaded() -> bool:
    result = subprocess.run(
        ["launchctl", "list", PLIST_LABEL],
        capture_output=True, text=True,
    )
    return result.returncode == 0


def get_schedule_info() -> Optional[dict]:
    if not PLIST_PATH.exists():
        return None
    with open(PLIST_PATH, "rb") as f:
        plist = plistlib.load(f)
    interval = plist.get("StartCalendarInterval", {})
    prog_args = plist.get("ProgramArguments", [])
    # Support all plist formats across versions:
    #   current: [python, launcher.py, check, ...args]
    #   v2:      [python, -m, new_ebooks, check, ...args]
    #   v1:      [script, check, ...args]
    if len(prog_args) >= 3 and prog_args[1] == str(LAUNCHER_PATH):
        check_args = prog_args[3:]
    elif len(prog_args) >= 4 and prog_args[1:3] == ["-m", "new_ebooks"]:
        check_args = prog_args[4:]
    else:
        check_args = prog_args[2:] if len(prog_args) > 2 else []
    return {
        "weekday": interval.get("Weekday", 0),
        "hour": interval.get("Hour", 0),
        "minute": interval.get("Minute", 0),
        "check_args": check_args,
        "loaded": is_loaded(),
    }
